### ISSUE TITLE
Actions で tests と real-tests の順番を入れ替える

### ISSUE THREAD

**Issue by solareenlo** [solareenlo/42libunit#4]
real-tests が成功しているかどうか分からないので，必ず失敗する tests を real-tests の後ろに持っていき，real-tests を先にテストする．

**Comment by Masaya-Kamei** [comment]
> real-tests が成功しているかどうか分からないので，必ず失敗する tests を real-tests の後ろに持っていき，real-tests を先にテストする．

実装しました！！

**Comment by solareenlo** [comment]
ありがとうございます！
~~プルリク投げてもいいですし，そのままマージしてもいいですし，やっちゃってくださいませ~~  🙇
